name: mck-exp
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28181
title: McKinney Experiential
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cccccc'
    - '#4679bb'
    - '#131217'
    - '#a58971'
    - '#940004'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
