name: mck-exp
favicon: null
layout_spectrum: 0.27634601201862097
typography_spectrum: 0.6473900533746928
title: McKinney Experiential
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#9da273'
    - '#685d49'
    - '#d3881b'
    - '#d6c300'
  brandStrength: 0.625
  lightness: 0.6808051243424416
  saturation: 0.48922473657876253
  rhythmicContrast: 0.5613675431814045
purpose: []
